### PR TITLE
Set env var to use only supported cflags

### PR DESCRIPTION
**Pull request by SimonCW**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Review by maciejkula — APPROVED** [review]
@SimonCW I just released LightFM v1.16 which supports the `LIGHTFM_NO_CFLAGS` setting.

There are a lot of changes here that I don't understand, but :+1: on the NO_CFLAGS setting.

**Comment by SimonCW** [comment]
Hi @maciejkula , the LIGHTFM_NO_CFLAGS is the only thing I changed myself. All other changes are from the automatic re-rendering `with conda-build 3.20.5, conda-smithy 3.8.5, ...`.

**Comment by maciejkula** [comment]
@SimonCW Sorry for being rusty on how this works - I released the flag additions in version 1.16 on PyPI, and they are not in 1.15. Do we need to bump the version here?

**Comment by SimonCW** [comment]
Hi @maciejkula, 

no worries, I'm just now learning how the whole conda-packaging works :). There is a bot that automatically creates a pull request whenever a new version is released on pypi, see: https://github.com/conda-forge/lightfm-feedstock/pull/10

I see two options: 
- We update the [automatically created PR](https://github.com/conda-forge/lightfm-feedstock/pull/10) by adding the `LIGHTFM_NO_CFLAGS ` to the bot's fork [lightfm v1.16](https://github.com/regro-cf-autotick-bot/lightfm-feedstock/tree/1.16_h3a1e26) and close this PR. @maciejkula , you would have to do that since I don't have permissions to modify the bot's fork. 
- We first merge the [update PR](https://github.com/conda-forge/lightfm-feedstock/pull/10), I update this PR, and then merge it afterwards.

**Pull request merged**
